version: '3.4'


services:
  postgres_db:
    container_name: postgres_db
    image:
      postgres:13.4-alpine
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "20m"
    env_file:
      - envs/database.env
    restart:
      on-failure

  frontend:
    build: ./Frontend
    ports:
      - 3000:3000
      - 443:443

  backend:
    container_name: backend
    build:
      context: Backend/
    command: bash -c "python /app/manage.py makemigrations && python /app/manage.py migrate --noinput && python /app/manage.py runserver_plus  0.0.0.0:8081 --cert /www.solopharma.shop.crt --key-file /www.solopharma.shop.key"
    volumes:
      - ./backend/:/app
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
    env_file:
      - envs/database.env
      - envs/backend.env
    restart:
      on-failure



