version: '3.4'

services:
  postgres_db:
    container_name: postgres_db
    image:
      postgres:13.4-alpine
    volumes:
      - .reli_db./postgres/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "20m"
    env_file:
      - envs/database.env
    restart: always

  frontend1:
    build: ./Frontend
    ports:
      - 80:80
    volumes:
      - ./backend/base_product_images:/data/www/base_product_images


  backend:
    container_name: backend
    build:
      context: backend/
    command: bash -c "python /app/manage.py makemigrations && python3 manage.py collectstatic --no-input && python /app/manage.py migrate --noinput && gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8081"
    volumes:
      - ./backend/:/app
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
    env_file:
      - envs/database.env
      - envs/backend.env
    restart: always
