# Generated by Django 5.1 on 2025-08-31 07:16

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='ALT-текст')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Ссылка при клике')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image_original', models.ImageField(upload_to=banners.models.banner_upload_to, verbose_name='Исходное изображение')),
                ('image_webp', models.ImageField(blank=True, editable=False, null=True, upload_to=banners.models.banner_webp_upload_to, verbose_name='Сгенерированный WebP 1230×400')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
