# Generated by Django 5.1 on 2025-08-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
    ]
