# Generated by Django 5.1 on 2025-09-22 05:35

import banners.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_options'),
        ('sellers', '0002_sellerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_original_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=banners.models.banner_mobile_upload_to, verbose_name='Исходное изображение (mobile)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_webp_mobile',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=banners.models.banner_webp_mobile_upload_to, verbose_name='Сгенерированный WebP 1230×400 (mobile)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Если задан, баннер относится к конкретному продавцу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='sellers.sellerprofile', verbose_name='Продавец (опционально)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_original',
            field=models.ImageField(upload_to=banners.models.banner_upload_to, verbose_name='Исходное изображение (desktop)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=banners.models.banner_webp_upload_to, verbose_name='Сгенерированный WebP 1230×400 (desktop)'),
        ),
    ]
