# Generated by Django 5.1 on 2025-08-20 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, help_text='Основной склад продавца (origin). Пока только CZ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sellers', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Дополнительные склады (для мульти-origin в будущем).', related_name='sellers', to='warehouses.warehouse'),
        ),
    ]
