# Generated by Django 5.1 on 2025-12-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerprofile_created_at_and_more'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sellers', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='warehouses.warehouse'),
        ),
        migrations.CreateModel(
            name='SellerOnboardingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(blank=True, choices=[('self_employed', 'Self-employed / Sole proprietor'), ('company', 'Company / Legal entity')], max_length=32, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Manager', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_applications', to=settings.AUTH_USER_MODEL)),
                ('seller_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_application', to='sellers.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('identity_document', 'Identity document'), ('proof_of_address', 'Proof of address'), ('registration_certificate', 'Registration certificate')], max_length=64)),
                ('scope', models.CharField(choices=[('self_employed_personal', 'Self-employed / Personal'), ('self_employed_address', 'Self-employed / Address'), ('company_info', 'Company / Info'), ('company_representative', 'Company / Representative'), ('company_address', 'Company / Address'), ('warehouse_address', 'Warehouse address'), ('return_address', 'Return address')], max_length=64)),
                ('side', models.CharField(blank=True, max_length=16, null=True)),
                ('file', models.FileField(upload_to='seller_onboarding_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCompanyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=2, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_form', models.CharField(blank=True, max_length=128, null=True)),
                ('country_of_registration', models.CharField(blank=True, max_length=2, null=True)),
                ('business_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ico', models.CharField(blank=True, max_length=32, null=True)),
                ('tin', models.CharField(blank=True, max_length=64, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('imports_to_eu', models.BooleanField(default=False)),
                ('eori_number', models.CharField(blank=True, max_length=64, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('proof_document_issue_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=11, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=32, null=True)),
                ('local_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerReturnAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_as_warehouse', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('proof_document_issue_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_address', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSelfEmployedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('proof_document_issue_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_employed_address', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSelfEmployedPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=2, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_employed_personal', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSelfEmployedTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_country', models.CharField(blank=True, max_length=2, null=True)),
                ('tin', models.CharField(blank=True, max_length=64, null=True)),
                ('ico', models.CharField(blank=True, max_length=32, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_employed_tax', to='sellers.selleronboardingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SellerWarehouseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('proof_document_issue_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_address', to='sellers.selleronboardingapplication')),
            ],
        ),
    ]
