# Generated by Django 5.1 on 2025-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_sellerprofile_default_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleronboardingapplication',
            name='current_step',
        ),
        migrations.AddConstraint(
            model_name='sellerdocument',
            constraint=models.UniqueConstraint(fields=('application', 'doc_type', 'scope', 'side'), name='unique_document_per_scope_side'),
        ),
    ]
