# Generated by Django 5.1 on 2026-02-02 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_remove_selleronboardingapplication_current_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('seller', 'Seller'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=16)),
                ('event_type', models.CharField(choices=[('section_updated', 'Section updated'), ('document_uploaded', 'Document uploaded'), ('document_replaced', 'Document replaced'), ('document_deleted', 'Document deleted'), ('review_requested', 'Review requested'), ('moderation_approved', 'Moderation approved'), ('moderation_rejected', 'Moderation rejected')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='sellers.selleronboardingapplication')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['application', 'created_at'], name='sellers_onb_applica_effaf8_idx'), models.Index(fields=['event_type', 'created_at'], name='sellers_onb_event_t_3bb10c_idx')],
            },
        ),
    ]
