# Generated by Django 5.1 on 2026-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_onboardingauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingauditlog',
            name='actor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
