# Generated by Django 5.1 on 2026-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_onboardingauditlog_actor_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdocument',
            name='identity_document_subtype',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('id_card', 'ID card'), ('driving_license', 'Driving license')], max_length=32, null=True),
        ),
    ]
