# Generated by Django 5.1 on 2026-04-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_sellerdocument_identity_document_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerselfemployedtaxinfo',
            old_name='ico',
            new_name='business_id',
        ),
    ]
