# Generated by Django 5.1 on 2026-04-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_rename_ico_sellerselfemployedtaxinfo_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellercompanyinfo',
            name='ico',
        ),
    ]
