# Generated by Django 5.1 on 2026-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_remove_sellercompanyinfo_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwarehouseaddress',
            name='same_as_primary_address',
            field=models.BooleanField(default=False),
        ),
    ]
