# Generated by Django 5.1 on 2026-06-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_sellerwarehouseaddress_same_as_primary_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingauditlog',
            name='event_type',
            field=models.CharField(choices=[('section_updated', 'Section updated'), ('document_uploaded', 'Document uploaded'), ('document_replaced', 'Document replaced'), ('document_deleted', 'Document deleted'), ('review_requested', 'Review requested'), ('moderation_approved', 'Moderation approved'), ('moderation_rejected', 'Moderation rejected'), ('ares_lookup', 'ARES lookup'), ('ares_verified', 'ARES verified'), ('ares_mismatch', 'ARES mismatch')], max_length=64),
        ),
        migrations.CreateModel(
            name='SellerAresVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_queried', models.CharField(max_length=32)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('field_matches', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ares_verification', to='sellers.selleronboardingapplication')),
            ],
            options={
                'verbose_name': 'Seller ARES verification',
                'verbose_name_plural': 'Seller ARES verifications',
            },
        ),
    ]
