# Generated by Django 5.1 on 2025-05-20 17:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('label_file', models.FileField(blank=True, null=True, upload_to='packeta_labels/')),
                ('weight_grams', models.PositiveIntegerField()),
                ('parcel_index', models.PositiveIntegerField(default=0, help_text='Порядковый номер посылки в рамках заказа')),
                ('shipping_price', models.DecimalField(decimal_places=2, help_text='Стоимость доставки для этой посылки', max_digits=10)),
                ('status', models.CharField(default='created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryParcelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('channel', models.CharField(choices=[('PUDO', 'Pick-up point'), ('HD', 'Home Delivery')], max_length=4)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('oversized', 'Oversized')], max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimate', models.CharField(blank=True, max_length=50)),
                ('weight_limit', models.CharField(choices=[('1', 'up to 1 kg'), ('2', 'up to 2 kg'), ('5', 'up to 5 kg'), ('10', 'up to 10 kg'), ('15', 'up to 15 kg'), ('over_limit', 'over limit')], default='5', help_text='Weight limit for the shipping rate', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
