# Generated by Django 5.1 on 2025-05-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('order', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='deliveryparcel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.courierservice'),
        ),
        migrations.AddField(
            model_name='deliveryparcel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='deliveryparcelitem',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderproduct'),
        ),
        migrations.AddField(
            model_name='deliveryparcelitem',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliveryparcel'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='courier_service',
            field=models.ForeignKey(help_text='Courier service this rate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='order.courierservice'),
        ),
    ]
