# Generated by Django 5.1 on 2025-04-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryaddress_deliveryparcelitem'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('channel', models.CharField(choices=[('PUDO', 'Pick-up point'), ('HD', 'Home Delivery')], max_length=4)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('oversized', 'Oversized')], max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimate', models.CharField(blank=True, max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.sellerprofile')),
            ],
        ),
    ]
