# Generated by Django 5.1 on 2025-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('order', '0004_alter_courierservice_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shippingrate',
            constraint=models.UniqueConstraint(fields=('courier_service', 'country', 'channel', 'category', 'weight_limit'), name='uniq_rate_per_courier_country_channel_category_weight'),
        ),
    ]
