# Generated by Django 5.1 on 2025-04-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_shippingrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='supplier',
        ),
    ]
