# Generated by Django 5.1 on 2025-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_shippingrate_uniq_rate_per_courier_country_channel_category_weight'),
        ('order', '0004_alter_courierservice_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shippingrate',
            name='uniq_rate_per_courier_country_channel_category_weight',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='address_bundle',
            field=models.CharField(blank=True, choices=[('one', '1 parcel / address'), ('multi', '2+ parcels / address')], default='one', help_text='GLS BusinessParcel: 1 vs 2+ parcels to the same address/date', max_length=8),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='weight_limit',
            field=models.CharField(choices=[('1', 'up to 1 kg'), ('2', 'up to 2 kg'), ('5', 'up to 5 kg'), ('10', 'up to 10 kg'), ('15', 'up to 15 kg'), ('20', 'up to 20 kg'), ('31_5', 'up to 31.5 kg'), ('over_limit', 'over limit')], default='5', help_text='Weight limit for the shipping rate', max_length=10),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['courier_service', 'country', 'channel', 'category'], name='rate_cccc_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingrate',
            constraint=models.UniqueConstraint(fields=('courier_service', 'country', 'channel', 'category', 'weight_limit', 'address_bundle'), name='uniq_rate_per_courier_country_channel_category_weight_bundle'),
        ),
    ]
