# Generated by Django 5.1 on 2025-05-01 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_shippingrate_supplier'),
        ('order', '0007_alter_courierservice_options_courierservice_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryparcel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.courierservice'),
        ),
        migrations.DeleteModel(
            name='CourierService',
        ),
    ]
