# Generated by Django 5.1 on 2025-10-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_shippingrate_weight_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='weight_limit',
            field=models.CharField(choices=[('1', 'up to 1 kg'), ('2', 'up to 2 kg'), ('3', 'up to 3 kg'), ('5', 'up to 5 kg'), ('10', 'up to 10 kg'), ('15', 'up to 15 kg'), ('20', 'up to 20 kg'), ('30', 'up to 30 kg'), ('31_5', 'up to 31.5 kg'), ('50', 'up to 50 kg'), ('over_limit', 'over limit')], default='5', help_text='Weight limit for the shipping rate', max_length=10),
        ),
    ]
