# Generated by Django 5.1 on 2025-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliveryparcel_service_delete_courierservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcel',
            name='parcel_index',
            field=models.PositiveIntegerField(default=0, help_text='Порядковый номер посылки в рамках заказа'),
        ),
        migrations.AddField(
            model_name='deliveryparcel',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость доставки для этой посылки', max_digits=10),
            preserve_default=False,
        ),
    ]
