# Generated by Django 5.1 on 2025-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryparcel_parcel_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryparcel',
            name='label_url',
        ),
        migrations.AddField(
            model_name='deliveryparcel',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to='packeta_labels/'),
        ),
    ]
