# Generated by Django 5.1 on 2025-10-30 18:56

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_shippingrate_weight_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryparcel',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to=delivery.models.parcel_label_upload_to),
        ),
    ]
