# Generated by Django 5.1 on 2025-05-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_deliveryparcel_label_url_and_more'),
        ('order', '0009_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='courier_service',
            field=models.ForeignKey(default=2, help_text='Courier service this rate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='order.courierservice'),
            preserve_default=False,
        ),
    ]
