# Generated by Django 5.1 on 2025-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_shippingrate_courier_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='weight_limit',
            field=models.CharField(choices=[('1', 'up to 1 kg'), ('2', 'up to 2 kg'), ('5', 'up to 5 kg'), ('10', 'up to 10 kg'), ('15', 'up to 15 kg'), ('over_limit', 'over limit')], default='5', help_text='Weight limit for the shipping rate', max_length=10),
        ),
    ]
