# Generated by Django 5.1 on 2025-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='variable_symbol',
            field=models.CharField(default='TEMP-VS-0000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
