# Generated by Django 5.0.6 on 2025-01-31 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_delivery_date'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('awaiting_assembly', 'Awaiting assembly'), ('awaiting_shipment', 'Awaiting shipment'), ('deliverable', 'Deliverable'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('controversial', 'Controversial')], default='awaiting_assembly', max_length=30),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
    ]
