# Generated by Django 5.1 on 2025-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderproduct_status_orderproduct_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packeta_address_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
