# Generated by Django 5.1 on 2025-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_invoice_variable_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierservice',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код службы (например, packeta, zasilkovna)', max_length=50, null=True, unique=True),
        ),
    ]
