# Generated by Django 5.1 on 2025-04-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_packeta_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='packeta_address_id',
            new_name='pickup_point_id',
        ),
    ]
