# Generated by Django 5.1 on 2025-04-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryaddress_deliveryparcelitem'),
        ('order', '0005_rename_packeta_address_id_order_pickup_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryaddress'),
        ),
    ]
