# Generated by Django 5.1 on 2025-09-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_invoicesequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_point_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
