# Generated by Django 5.1 on 2026-01-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_pickup_point_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Order Created'), ('payment_confirmed', 'Payment Confirmed'), ('order_acknowledged', 'Order Acknowledged'), ('shipment_created', 'Shipment Created'), ('tracking_uploaded', 'Tracking Uploaded'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.order')),
            ],
        ),
    ]
