# Generated by Django 5.1 on 2025-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierservice',
            options={'ordering': ('name',), 'verbose_name': 'Courier Service', 'verbose_name_plural': 'Courier Services'},
        ),
        migrations.AddField(
            model_name='courierservice',
            name='active',
            field=models.BooleanField(default=True, help_text='Включена ли служба для выбора в интерфейсах'),
        ),
        migrations.AddField(
            model_name='courierservice',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код службы (например, packeta, zasilkovna)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courierservice',
            name='name',
            field=models.CharField(help_text='Читабельное имя службы (например, Packeta, Zásilkovna)', max_length=100),
        ),
    ]
