# Generated by Django 5.1 on 2025-05-12 06:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_courierservice_options_courierservice_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Итоговая сумма группы: товары + доставка.', max_digits=10),
        ),
    ]
