# Generated by Django 5.1 on 2025-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default='Test City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='CZ', max_length=2),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pickup_by_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street',
            field=models.CharField(default='00000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='zip_code',
            field=models.CharField(default='CZ', max_length=20),
            preserve_default=False,
        ),
    ]
