# Generated by Django 5.1 on 2025-05-21 08:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Определяет, активен ли продукт (если False — не отображается на витрине)'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='is_age_restricted',
            field=models.BooleanField(default=False, help_text='Требует ли товар возрастного ограничения 18+'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Процент НДС для товара (например: 0, 10, 21)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.99'))]),
        ),
    ]
