# Generated by Django 5.1 on 2025-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_baseproduct_is_active_baseproduct_is_age_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
