# Generated by Django 5.1 on 2026-06-08 07:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_baseproduct_additional_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand'),
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_documents/')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('document_type', models.CharField(choices=[('license', 'License'), ('certificate', 'Certificate'), ('instruction', 'Instruction'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='product.baseproduct')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('gtin', 'GTIN'), ('ean', 'EAN'), ('upc', 'UPC'), ('mpn', 'MPN'), ('seller_sku', 'Seller SKU'), ('marketplace_item_id', 'Marketplace item ID'), ('other', 'Other')], max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='product.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_media', to='product.baseproductimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.baseproduct')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='brand_name_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['status', 'name'], name='brand_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_brand_name_ci'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['product', 'status', 'sort_order'], name='pd_product_status_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['product', 'document_type'], name='pd_product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['status'], name='pd_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productexternalidentifier',
            index=models.Index(fields=['product', 'identifier_type'], name='pei_product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productexternalidentifier',
            index=models.Index(fields=['product', 'is_primary'], name='pei_product_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='productexternalidentifier',
            index=models.Index(fields=['identifier_type', 'value'], name='pei_type_value_idx'),
        ),
        migrations.AddIndex(
            model_name='productexternalidentifier',
            index=models.Index(fields=['source'], name='pei_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='productexternalidentifier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('value'), models.F('identifier_type'), name='uniq_pei_type_value_ci'),
        ),
        migrations.AddConstraint(
            model_name='productexternalidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'identifier_type'), name='uniq_pei_primary_type'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'sort_order'], name='pm_product_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'status', 'sort_order'], name='pm_product_status_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'media_type'], name='pm_product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['status'], name='pm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='uniq_main_media_per_product'),
        ),
    ]
