# Generated by Codex for Iteration 4 product catalog modernization.
#
# Production prerequisites, per ADR 08:
# - create a database backup before running this migration;
# - dry-run the migration plan on staging or a production-like database copy;
# - verify BaseProductImage count and legacy ProductMedia count after migration.

from django.db import migrations


def migrate_legacy_images_to_product_media(apps, schema_editor):
    BaseProductImage = apps.get_model('product', 'BaseProductImage')
    ProductMedia = apps.get_model('product', 'ProductMedia')

    existing_legacy_ids = set(
        ProductMedia.objects.exclude(legacy_image_id__isnull=True)
        .values_list('legacy_image_id', flat=True)
    )
    product_ids_with_main_media = set(
        ProductMedia.objects.filter(is_main=True).values_list('product_id', flat=True)
    )

    media_rows = []
    current_product_id = None
    sort_order = 0

    legacy_images = (
        BaseProductImage.objects.exclude(id__in=existing_legacy_ids)
        .order_by('product_id', 'id')
        .values('id', 'product_id', 'image')
    )

    for legacy_image in legacy_images.iterator():
        product_id = legacy_image['product_id']
        if product_id != current_product_id:
            current_product_id = product_id
            sort_order = 0

        is_main = sort_order == 0 and product_id not in product_ids_with_main_media
        media_rows.append(
            ProductMedia(
                product_id=product_id,
                file=legacy_image['image'],
                legacy_image_id=legacy_image['id'],
                media_type='image',
                sort_order=sort_order,
                is_main=is_main,
                status='approved',
            )
        )
        if is_main:
            product_ids_with_main_media.add(product_id)
        sort_order += 1

    ProductMedia.objects.bulk_create(media_rows, batch_size=500)


def reverse_legacy_images_to_product_media(apps, schema_editor):
    ProductMedia = apps.get_model('product', 'ProductMedia')
    ProductMedia.objects.exclude(legacy_image_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_baseproduct_brand_productdocument_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_images_to_product_media,
            reverse_legacy_images_to_product_media,
        ),
    ]
