# Generated by Django 5.1 on 2025-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_baseproduct_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='height_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Высота упаковки в миллиметрах', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Длина упаковки в миллиметрах', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0, help_text='Вес товара в граммах'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина упаковки в миллиметрах', null=True),
        ),
    ]
