# Generated by Django 5.1 on 2026-06-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_migrate_legacy_images_to_product_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allows_product_assignment',
            field=models.BooleanField(default=False, help_text='Разрешает создавать товары прямо в non-leaf категории.'),
        ),
        migrations.CreateModel(
            name='CategoryAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('enum', 'Enum')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='product.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.categoryattributedefinition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='product.categoryattributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.baseproduct')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='product.categoryattributeoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='categoryattributedefinition',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='cad_category_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattributedefinition',
            index=models.Index(fields=['category', 'code'], name='cad_category_code_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattributedefinition',
            index=models.Index(fields=['is_filterable', 'data_type'], name='cad_filter_type_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattributedefinition',
            index=models.Index(fields=['data_type'], name='cad_data_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattributedefinition',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uniq_cad_category_code'),
        ),
        migrations.AddIndex(
            model_name='categoryattributeoption',
            index=models.Index(fields=['attribute_definition', 'is_active', 'sort_order'], name='cao_attr_active_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute_definition', 'value'), name='uniq_cao_attr_value'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute_definition'], name='pav_product_attr_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute_definition', 'value_number'], name='pav_attr_number_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute_definition', 'value_boolean'], name='pav_attr_boolean_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute_definition', 'value_option'], name='pav_attr_option_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['source'], name='pav_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_definition'), name='uniq_pav_product_attr'),
        ),
    ]
