# Generated by Django 5.1 on 2026-06-12 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_allows_product_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty duration in months. Empty means not specified.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
