# Generated by Django 5.1 on 2025-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
