# Generated by Django 5.1 on 2025-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paypalmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('invoice_data', models.JSONField(blank=True, null=True)),
                ('description_data', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
