# Generated by Django 5.1 on 2026-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_session_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('payment_system', 'session_id'), name='payment_payment_system_session_id_uniq'),
        ),
    ]
