# Generated by Django 5.1 on 2025-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_stripemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalmetadata',
            name='products',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
