# Generated by Django 5.1 on 2025-05-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paypalmetadata_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalmetadata',
            name='products',
        ),
    ]
