# Generated by Django 5.1 on 2025-05-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_paypalmetadata_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripemetadata',
            name='products',
        ),
    ]
